### ISSUE TITLE
Not working "mvn clean package" command 

### ISSUE THREAD

**Issue by jfernandezsqs** [International-Data-Spaces-Association/metadata-broker-open-core#86]
I have an old version of the metada-broker-open-core with the 4.2.8-SNAPSHOT and when I execute the command 
> mvn clean package

It gives me the following error:
>sqs@sqs-VirtualBox:~/MetadataBroker$ mvn clean package
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] broker-open-core                                                   [pom]
[INFO] open-index-common                                                  [jar]
[INFO] open-broker-common                                                 [jar]
[INFO] broker-core                                                        [jar]
[INFO] 
[INFO] ------------< de.fraunhofer.iais.eis.ids:broker-open-core >-------------
[INFO] Building broker-open-core 4.2.8-SNAPSHOT                           [1/4]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ broker-open-core ---
[INFO] 
[INFO] --- flatten-maven-plugin:1.2.2:clean (flatten.clean) @ broker-open-core ---
[INFO] Deleting /home/sqs/TESTBED_7.0.0/MetadataBroker_old/.flattened-pom.xml
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:prepare-agent (prepare-agent) @ broker-open-core ---
[INFO] argLine set to -javaagent:/home/sqs/.m2/repository/org/jacoco/org.jacoco.agent/0.8.6/org.jacoco.agent-0.8.6-runtime.jar=destfile=/home/sqs/TESTBED_7.0.0/MetadataBroker_old/target/jacoco.exec
[INFO] 
[INFO] --- flatten-maven-plugin:1.2.2:flatten (flatten) @ broker-open-core ---
[INFO] Generating flattened POM of project de.fraunhofer.iais.eis.ids:broker-open-core:pom:4.2.8-SNAPSHOT...
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:report (report) @ broker-open-core ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO] 
[INFO] ------------< de.fraunhofer.iais.eis.ids:open-index-common >------------
[INFO] Building open-index-common 4.2.8-SNAPSHOT                          [2/4]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from eis-public-repo: http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/core/4.2.8-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata de.fraunhofer.iais.eis.ids:core:4.2.8-SNAPSHOT/maven-metadata.xml from/to eis-public-repo (http://maven.iais.fraunhofer.de/artifactory/eis-ids-public): Transfer failed for http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/core/4.2.8-SNAPSHOT/maven-metadata.xml
[WARNING] Failure to transfer de.fraunhofer.iais.eis.ids:core:4.2.8-SNAPSHOT/maven-metadata.xml from http://maven.iais.fraunhofer.de/artifactory/eis-ids-public was cached in the local repository, resolution will not be reattempted until the update interval of eis-public-repo has elapsed or updates are forced. Original error: Could not transfer metadata de.fraunhofer.iais.eis.ids:core:4.2.8-SNAPSHOT/maven-metadata.xml from/to eis-public-repo (http://maven.iais.fraunhofer.de/artifactory/eis-ids-public): Transfer failed for http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/core/4.2.8-SNAPSHOT/maven-metadata.xml
Downloading from eis-public-repo: http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/core/4.2.8-SNAPSHOT/core-4.2.8-SNAPSHOT.pom
Downloading from eis-public-repo: http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/connector-commons/4.2.8-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata de.fraunhofer.iais.eis.ids:connector-commons:4.2.8-SNAPSHOT/maven-metadata.xml from/to eis-public-repo (http://maven.iais.fraunhofer.de/artifactory/eis-ids-public): Transfer failed for http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/connector-commons/4.2.8-SNAPSHOT/maven-metadata.xml
[WARNING] Failure to transfer de.fraunhofer.iais.eis.ids:connector-commons:4.2.8-SNAPSHOT/maven-metadata.xml from http://maven.iais.fraunhofer.de/artifactory/eis-ids-public was cached in the local repository, resolution will not be reattempted until the update interval of eis-public-repo has elapsed or updates are forced. Original error: Could not transfer metadata de.fraunhofer.iais.eis.ids:connector-commons:4.2.8-SNAPSHOT/maven-metadata.xml from/to eis-public-repo (http://maven.iais.fraunhofer.de/artifactory/eis-ids-public): Transfer failed for http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/connector-commons/4.2.8-SNAPSHOT/maven-metadata.xml
Downloading from eis-public-repo: http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/connector-commons/4.2.8-SNAPSHOT/connector-commons-4.2.8-SNAPSHOT.pom
Downloading from eis-public-repo: http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/interaction/4.2.8-SNAPSHOT/maven-metadata.xml

It seems to be a problem with the eis-public-repo  --> http://maven.iais.fraunhofer.de/artifactory/eis-ids-public

**Comment by SebastianOpriel** [comment]
@sebbader I face similar problems with DSC v7.0.1

```
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< io:dataspaceconnector >------------------------
[INFO] Building Dataspace Connector 7.0.1
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from eis-public-repo: http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/infomodel/util/4.2.7-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata de.fraunhofer.iais.eis.infomodel:util:4.2.7-SNAPSHOT/maven-metadata.xml from/to eis-public-repo (http://maven.iais.fraunhofer.de/artifactory/eis-ids-public): Transfer failed for http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/infomodel/util/4.2.7-SNAPSHOT/maven-metadata.xml
[WARNING] Failure to transfer de.fraunhofer.iais.eis.infomodel:util:4.2.7-SNAPSHOT/maven-metadata.xml from http://maven.iais.fraunhofer.de/artifactory/eis-ids-public was cached in the local repository, resolution will not be reattempted until the update interval of eis-public-repo has elapsed or updates are forced. Original error: Could not transfer metadata de.fraunhofer.iais.eis.infomodel:util:4.2.7-SNAPSHOT/maven-metadata.xml from/to eis-public-repo (http://maven.iais.fraunhofer.de/artifactory/eis-ids-public): Transfer failed for http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/infomodel/util/4.2.7-SNAPSHOT/maven-metadata.xml
```

Might this have to do with the bug I reported already here: https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/issues/78

**Comment by sebbader** [comment]
Hi guys, thanks for reporting! Should be fixed with https://github.com/International-Data-Spaces-Association/metadata-broker-open-core/pull/79

**Comment by sebbader** [comment]
@NehaThawani44 or Marie, please confirm that and then close the issue.

**Comment by jfernandezsqs** [comment]
I have tried with the latest update of the metadatabroker and the mvn celan package command is still not working.
I attach the logs here
> sqs@dellxps:~/TESTBED_WIP/metadata-broker-open-core$ mvn clean package
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] broker-open-core                                                   [pom]
[INFO] open-index-common                                                  [jar]
[INFO] open-broker-common                                                 [jar]
[INFO] broker-core                                                        [jar]
[INFO] 
[INFO] ------------< de.fraunhofer.iais.eis.ids:broker-open-core >-------------
[INFO] Building broker-open-core 5.0.0-SNAPSHOT                           [1/4]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ broker-open-core ---
[INFO] 
[INFO] --- flatten-maven-plugin:1.2.2:clean (flatten.clean) @ broker-open-core ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:prepare-agent (prepare-agent) @ broker-open-core ---
[INFO] argLine set to -javaagent:/home/sqs/.m2/repository/org/jacoco/org.jacoco.agent/0.8.6/org.jacoco.agent-0.8.6-runtime.jar=destfile=/home/sqs/TESTBED_WIP/metadata-broker-open-core/target/jacoco.exec
[INFO] 
[INFO] --- flatten-maven-plugin:1.2.2:flatten (flatten) @ broker-open-core ---
[INFO] Generating flattened POM of project de.fraunhofer.iais.eis.ids:broker-open-core:pom:5.0.0-SNAPSHOT...
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:report (report) @ broker-open-core ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO] 
[INFO] ------------< de.fraunhofer.iais.eis.ids:open-index-common >------------
[INFO] Building open-index-common 5.0.0-SNAPSHOT                          [2/4]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from eis-public-repo: https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/core/5.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from eis-public-repo: https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/core/5.0.0-SNAPSHOT/maven-metadata.xml (994 B at 1.6 kB/s)
Downloading from eis-public-repo: https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel/java/5.0.0-SNAPSHOT/maven-metadata.xml
Downloading from eis-snapshot-repo: http://maven.iais.fraunhofer.de/artifactory/eis-ids-snapshot/de/fraunhofer/iais/eis/ids/infomodel/java/5.0.0-SNAPSHOT/maven-metadata.xml
Downloading from eis-ids-public: http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel/java/5.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from eis-public-repo: https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel/java/5.0.0-SNAPSHOT/maven-metadata.xml (1.2 kB at 7.1 kB/s)
[WARNING] Could not transfer metadata de.fraunhofer.iais.eis.ids.infomodel:java:5.0.0-SNAPSHOT/maven-metadata.xml from/to eis-snapshot-repo (http://maven.iais.fraunhofer.de/artifactory/eis-ids-snapshot): Transfer failed for http://maven.iais.fraunhofer.de/artifactory/eis-ids-snapshot/de/fraunhofer/iais/eis/ids/infomodel/java/5.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata de.fraunhofer.iais.eis.ids.infomodel:java:5.0.0-SNAPSHOT/maven-metadata.xml from/to eis-ids-public (http://maven.iais.fraunhofer.de/artifactory/eis-ids-public): Transfer failed for http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel/java/5.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Failure to transfer de.fraunhofer.iais.eis.ids.infomodel:java:5.0.0-SNAPSHOT/maven-metadata.xml from http://maven.iais.fraunhofer.de/artifactory/eis-ids-snapshot was cached in the local repository, resolution will not be reattempted until the update interval of eis-snapshot-repo has elapsed or updates are forced. Original error: Could not transfer metadata de.fraunhofer.iais.eis.ids.infomodel:java:5.0.0-SNAPSHOT/maven-metadata.xml from/to eis-snapshot-repo (http://maven.iais.fraunhofer.de/artifactory/eis-ids-snapshot): Transfer failed for http://maven.iais.fraunhofer.de/artifactory/eis-ids-snapshot/de/fraunhofer/iais/eis/ids/infomodel/java/5.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Failure to transfer de.fraunhofer.iais.eis.ids.infomodel:java:5.0.0-SNAPSHOT/maven-metadata.xml from http://maven.iais.fraunhofer.de/artifactory/eis-ids-public was cached in the local repository, resolution will not be reattempted until the update interval of eis-ids-public has elapsed or updates are forced. Original error: Could not transfer metadata de.fraunhofer.iais.eis.ids.infomodel:java:5.0.0-SNAPSHOT/maven-metadata.xml from/to eis-ids-public (http://maven.iais.fraunhofer.de/artifactory/eis-ids-public): Transfer failed for http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel/java/5.0.0-SNAPSHOT/maven-metadata.xml
Downloading from eis-public-repo: https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel/java/5.0.0-SNAPSHOT/java-5.0.0-20220208.152137-10.pom
Downloaded from eis-public-repo: https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel/java/5.0.0-SNAPSHOT/java-5.0.0-20220208.152137-10.pom (1.7 kB at 4.7 kB/s)
Downloading from eis-snapshot-repo: http://maven.iais.fraunhofer.de/artifactory/eis-ids-snapshot/de/fraunhofer/iais/eis/infomodel/util/5.0.0-SNAPSHOT/maven-metadata.xml
Downloading from eis-public-repo: https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/infomodel/util/5.0.0-SNAPSHOT/maven-metadata.xml
Downloading from eis-ids-public: http://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/infomodel/util/5.0.0-SNAPSHOT/maven-metadata.xml
Downloaded from eis-public-repo: https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/de/fraunhofer/iais/eis/infomodel/util/5.0.0-SNAPSHOT/maven-metadata.xml (1.0 kB at 6.2 kB/s)

**Comment by NehaThawani44** [comment]
@jfernandezsqs  This looks to me like a local setup error I cannot see the exact DAPS error anywhere.

**Comment by aitorce** [comment]
The issue we have is we are having a completely local Testbed. We need to use "mvn clean package" to create the snapshot with our local `isstbroker-keystore.jks` and `daps.crt`. They both have certificates from our local Certificate Authority and without this snapshot, we cannot create our own `registry.gitlab.cc-asp.fraunhofer.de/eis-ids/broker-open/core` image.

**Comment by NehaThawani44** [comment]
Okay so this is not a certificate problem but a project setup issue, I see that from logs.

**Comment by sebplorenz** [comment]
Hi @NehaThawani44, what happens is that when you run "mvn compile" on this source then:

1. maven starts and finds a dependency to de.fraunhofer.iais.eis.ids:core:5.0.0-SNAPSHOT
2. it downloads de.fraunhofer.iais.eis.ids:core:5.0.0-SNAPSHOT from https://maven.iais.fraunhofer.de/artifactory/eis-ids-public because with #79 the repository url was fixed
3. maven checks the pom of the downloaded de.fraunhofer.iais.eis.ids:core:5.0.0-SNAPSHOT and sees that it depends on infomodel and has the old snapshot repository **_http_:**//maven.iais.fraunhofer.de/artifactory/eis-ids-public configured
4. maven tries to download the infomodel from **_http_:**//maven.iais.fraunhofer.de/artifactory/eis-ids-public configured in core and fails

Therefore you have to apply the same fix as #79 did on this respository to all of the IAIS dependencies that this repo has. Meaning all (transitive) maven dependencies with groupId de.fraunhofer.iais.eis.ids that this repo depends on.
